// <auto-generated />
namespace CourseWorkDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _4in1v2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4in1v2));
        
        string IMigrationMetadata.Id
        {
            get { return "201810101600230_4 in 1 v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
